version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.22-git
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache python3 bash && ln -sf python3 /usr/bin/python
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip3 install awscli
            
      - run:
          name: Build application Docker image
          environment:
            IMAGE_NAME: ysfbmgateway
          command: |
            docker build . -t ${IMAGE_NAME} 
            docker tag ${IMAGE_NAME} ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}
            docker tag ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1} shaposhnikoff/${IMAGE_NAME}:latest

      - deploy:
          name: Push application Docker image
          environment:
            IMAGE_NAME: ysfbmgateway
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              login="$(docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD)"
              ${login}
              docker push shaposhnikoff/${IMAGE_NAME}:${CIRCLE_SHA1}
              docker push shaposhnikoff/${IMAGE_NAME}:latest
              #login="$(aws ecr get-login)"
              #${login}
              #docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
              #docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            fi
