version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip3 install awscli
      - run: | 
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 
      - run:
          name: Build application Docker image
          environment:
            IMAGE_NAME: ysfbmgateway
          command: |
            docker tag ${IMAGE_NAME} ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}
            docker tag ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1} shaposhnikoff/${IMAGE_NAME}:latest
            
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker push shaposhnikoff/${IMAGE_NAME}:${CIRCLE_SHA1}
              docker push shaposhnikoff/${IMAGE_NAME}:latest
            fi






