version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.22-git
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache python3 bash && ln -sf python3 /usr/bin/python
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip3 install awscli
            
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      
      - run: 
          name: biuld and push
          environment:
            IMAGE_NAME: ysfbmgateway
          command: |
          docker build -t ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1} .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}
