version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.22-git
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache python3 bash && ln -sf python3 /usr/bin/python
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip3 install awscli
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true      
      - run: 
          name: biuld and push
          environment:
            IMAGE_NAME: ysfbmgateway
          command: |
            docker build -t ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1} .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            #docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker push ${CIRCLE_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}
