version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: mydockerhub-user  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference      
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip3 install awscli
      - run:
          name: Build application Docker image
          command: |
            docker build -t ysfbmgateway .
            docker tag ysfbmgateway shaposhnikoff/ysfbmgateway:${CIRCLE_SHA1}
            docker tag shaposhnikoff/ysfbmgateway:${CIRCLE_SHA1} shaposhnikoff/ysfbmgateway:latest
            
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker push shaposhnikoff/ysfbmgateway:${CIRCLE_SHA1}
              docker push shaposhnikoff/ysfbmgateway:latest
            fi



